CREATE ROLE demodb_owner LOGIN
  NOSUPERUSER NOINHERIT NOCREATEDB CREATEROLE NOREPLICATION;

CREATE ROLE demodb_user LOGIN
  NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

\set ON_ERROR_STOP true

CREATE DATABASE :new_database WITH OWNER demodb_owner;

\connect :new_database

CREATE EXTENSION "uuid-ossp";
-- CREATE EXTENSION postgis;
-- CREATE EXTENSION adminpack;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO demodb_owner;
GRANT ALL ON SCHEMA public TO PUBLIC;
